### ISSUE TITLE
Routing a root block doesn't work

### ISSUE THREAD

**Issue by RX14** [repomaa/crouter#3]
``` crystal
class MyRouter < Crouter::Router
  get "/" do
    context.response << "Hello World"
  end
end
```

Routing a `GET /` in this router fails because the regex [here](https://github.com/jreinert/crouter/blob/master/src/crouter/router.cr#L47) matches the single `"/"` and transforms it to `""` which doesn't route.

**Comment by repomaa** [comment]
That's weird. Matching always cuts the last `/` from the path (if present) and matches against the routes without it. So the static part should be `""`. The request coming in would have the path `"/"` or `""`, not sure. Anyways it should then result in the same static part and also match against the route. So you get a 404? Or does it refuse to compile altogether?

**Comment by RX14** [comment]
I get a 404, it just doesn't work.
