### ISSUE TITLE
PUT and DELETE method in Form

### ISSUE THREAD

**Issue by bthachdev** [repomaa/crouter#9]
In other web framework, we can use hidden field to check put or delete method
<input type="hidden" name="_method" value="PUT">

How can we do that in crouter?

**Comment by repomaa** [comment]
no you can't but i'd be happy to accept a pull request

**Comment by repomaa** [comment]
@bthachdev i'd recommend adding a middleware before crouter which will check if it's a posted form and set the method of the request to whatever is in the _method param (or leave it at post if unset)
